# Generated by Django 5.2.16 on 2026-09-28 20:31

import common.identifiers
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_country_centroid_country_currency_symbol_and_more'),
        ('restaurants', '0009_restaurant_auto_dispatch_couriers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneOpeningHours',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.SmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opens_at', models.TimeField()),
                ('closes_at', models.TimeField()),
            ],
            options={
                'verbose_name': 'horaire de zone',
                'verbose_name_plural': 'horaires de zone',
                'ordering': ['weekday', 'opens_at'],
            },
        ),
        migrations.CreateModel(
            name='ZoneScheduleException',
            fields=[
                ('id', models.UUIDField(default=common.identifiers.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('closed', 'Fermeture exceptionnelle'), ('open', 'Ouverture exceptionnelle')], max_length=8)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': "exception d'horaires de zone",
                'verbose_name_plural': "exceptions d'horaires de zone",
                'ordering': ['starts_at'],
            },
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En revue'), ('published', 'Publiée'), ('suspended', 'Suspendue'), ('archived', 'Archivée')], default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='suspension_expected_end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deliveryzone',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='estimated_delivery_minutes',
            field=models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='zoneopeninghours',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='geography.deliveryzone'),
        ),
        migrations.AddField(
            model_name='zonescheduleexception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='zonescheduleexception',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='geography.deliveryzone'),
        ),
        migrations.AddConstraint(
            model_name='zoneopeninghours',
            constraint=models.UniqueConstraint(fields=('zone', 'weekday', 'opens_at'), name='zone_hours_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='zoneopeninghours',
            constraint=models.CheckConstraint(condition=models.Q(('opens_at', models.F('closes_at')), _negated=True), name='zone_hours_not_empty'),
        ),
        migrations.AddIndex(
            model_name='zonescheduleexception',
            index=models.Index(fields=['zone', 'ends_at'], name='zone_exception_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='zonescheduleexception',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='zone_exception_ends_after_start'),
        ),
    ]
