// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// ⚠️ **Valeurs de remplissage, pas des identifiants réels.**
///
/// L'en-tête « File generated by FlutterFire CLI » a été retiré le 2026-08-05 :
/// il était faux et se lisait comme une garantie. Les clés sont factices
/// (`AIzaSyDummyKeyForTesting`) et le projet nommé ici, `fastfoodgo-deliver`,
/// n'existe pas — aucun projet Firebase n'a encore été créé pour El Corazón.
/// La documentation annonçait `dely` comme « déjà configuré » sur la foi de ce
/// seul en-tête.
///
/// À remplacer intégralement par `flutterfire configure` — ne pas éditer les
/// valeurs à la main. La marche à suivre est dans `docs/firebase.md`. Tant que
/// c'est le cas, `Firebase.initializeApp()` échoue au démarrage : `main()` et
/// `NotificationService` traitent cet échec comme non fatal (l'application
/// tourne, sans notifications push) plutôt que de bloquer le lancement.
///
/// `El Corazon fastfood/lib/firebase_options.dart` est dans le même état.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbt_ZYvbzUwmcflqiHH8GL8BdAlAImlqI',
    appId: '1:574529156682:web:47024d329f15b37c8458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    authDomain: 'elcorazon-9595.firebaseapp.com',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByYPmtsEhRXWbmHQDtNLpHkw7IKpTwo10',
    appId: '1:574529156682:android:5af0f6aee41c72f28458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_u76eEunEsbuCJFqE3juV9RrwWeJ-CU',
    appId: '1:574529156682:ios:eb4472f9af7287998458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
    iosBundleId: 'com.elcorazon.dely',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_u76eEunEsbuCJFqE3juV9RrwWeJ-CU',
    appId: '1:574529156682:ios:11c28630bcd706398458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
    iosBundleId: 'com.example.elcoraDely',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForTesting',
    appId: '1:123456789:windows:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'fastfoodgo-deliver',
    authDomain: 'fastfoodgo-deliver.firebaseapp.com',
    storageBucket: 'fastfoodgo-deliver.appspot.com',
  );
}
