import 'package:flutter/material.dart';
import 'package:flutter_rating_bar/flutter_rating_bar.dart';
import 'package:provider/provider.dart';
import 'package:elcora_fast/models/order.dart';
import 'package:elcora_fast/services/app_service.dart';
import 'package:elcora_fast/services/driver_rating_service.dart';
import 'package:elcora_fast/services/review_rating_service.dart';
import 'package:elcora_fast/widgets/custom_button.dart';

class OrderRatingScreen extends StatefulWidget {
  final Order order;

  const OrderRatingScreen({
    required this.order,
    super.key,
  });

  @override
  State<OrderRatingScreen> createState() => _OrderRatingScreenState();
}

class _OrderRatingScreenState extends State<OrderRatingScreen> {
  // Driver Rating State
  double _driverRating = 0;
  final _driverCommentController = TextEditingController();

  // Items Rating State
  final Map<String, double> _itemRatings = {};
  final Map<String, TextEditingController> _itemComments = {};

  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // Initialize controllers for each item
    for (final item in widget.order.items) {
      _itemComments[item.menuItemId] = TextEditingController();
      _itemRatings[item.menuItemId] = 0;
    }
  }

  @override
  void dispose() {
    _driverCommentController.dispose();
    for (final controller in _itemComments.values) {
      controller.dispose();
    }
    super.dispose();
  }

  Future<void> _submitRatings() async {
    setState(() => _isLoading = true);

    try {
      final appService = Provider.of<AppService>(context, listen: false);
      final driverRatingService = DriverRatingService();
      final reviewRatingService =
          Provider.of<ReviewRatingService>(context, listen: false);
      final currentUser = appService.currentUser;

      if (currentUser == null) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Erreur: Utilisateur non connecté')),
          );
        }
        return;
      }

      int successCount = 0;
      int totalActions = 0;

      // 1. Submit Driver Rating (if rated)
      if (_driverRating > 0 && widget.order.deliveryPersonId != null) {
        totalActions++;
        final success = await driverRatingService.submitRating(
          driverId: widget.order.deliveryPersonId!,
          orderId: widget.order.id,
          customerId: currentUser.id,
          rating: _driverRating.toInt(),
          comment: _driverCommentController.text.trim(),
        );
        if (success) successCount++;
      }

      // 2. Submit Item Ratings (only those with a rating > 0)
      for (final item in widget.order.items) {
        final rating = _itemRatings[item.menuItemId] ?? 0;
        if (rating > 0) {
          totalActions++;

          // Check if verified purchase (should be true since we are rating a completed order)
          const hasPurchased = true;

          final review = ProductReview(
            id: '', // Will be generated by DB or ignored on insert
            menuItemId: item.menuItemId,
            userId: currentUser.id,
            userName: currentUser.name,
            rating: rating,
            title: '', // Optional title
            comment: _itemComments[item.menuItemId]?.text.trim() ?? '',
            isVerifiedPurchase: hasPurchased,
            createdAt: DateTime.now(),
          );

          final success = await reviewRatingService.addReview(review);
          if (success) successCount++;
        }
      }

      if (mounted) {
        if (totalActions == 0) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Veuillez noter au moins un élément')),
          );
        } else if (successCount > 0) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Merci pour vos avis !')),
          );
          Navigator.of(context).pop();
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Erreur lors de l\'envoi des avis')),
          );
        }
      }
    } catch (e) {
      debugPrint('Error submitting ratings: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Une erreur est survenue')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Noter la commande'),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (widget.order.deliveryPersonId != null) ...[
              _buildDriverRatingSection(),
              const SizedBox(height: 24),
              const Divider(),
              const SizedBox(height: 24),
            ],
            _buildItemsRatingSection(),
            const SizedBox(height: 32),
            CustomButton(
              text: 'Envoyer les avis',
              onPressed: _submitRatings,
              isLoading: _isLoading,
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }

  Widget _buildDriverRatingSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Le Livreur',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
        ),
        const SizedBox(height: 16),
        Row(
          children: [
            CircleAvatar(
              radius: 30,
              backgroundColor: Colors.grey[200],
              child: const Icon(Icons.person, size: 30, color: Colors.grey),
            ),
            const SizedBox(width: 16),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Livreur', // We might want to pass driver name in Order object if available
                    style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    'Comment s\'est passée la livraison ?',
                    style: TextStyle(color: Colors.grey[600], fontSize: 12),
                  ),
                ],
              ),
            ),
          ],
        ),
        const SizedBox(height: 16),
        Center(
          child: RatingBar.builder(
            initialRating: _driverRating,
            minRating: 1,
            itemPadding: const EdgeInsets.symmetric(horizontal: 4.0),
            itemBuilder: (context, _) => const Icon(
              Icons.star,
              color: Colors.amber,
            ),
            onRatingUpdate: (rating) {
              setState(() {
                _driverRating = rating;
              });
            },
          ),
        ),
        const SizedBox(height: 16),
        TextField(
          controller: _driverCommentController,
          decoration: InputDecoration(
            hintText: 'Commentaire sur la livraison (optionnel)',
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            filled: true,
            fillColor: Colors.grey[50],
          ),
          maxLines: 2,
        ),
      ],
    );
  }

  Widget _buildItemsRatingSection() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          'Les Plats',
          style: Theme.of(context).textTheme.titleLarge?.copyWith(
                fontWeight: FontWeight.bold,
              ),
        ),
        const SizedBox(height: 16),
        ListView.separated(
          shrinkWrap: true,
          physics: const NeverScrollableScrollPhysics(),
          itemCount: widget.order.items.length,
          separatorBuilder: (context, index) => const SizedBox(height: 24),
          itemBuilder: (context, index) {
            final item = widget.order.items[index];
            return _buildItemRatingCard(item);
          },
        ),
      ],
    );
  }

  Widget _buildItemRatingCard(OrderItem item) {
    return Card(
      elevation: 0,
      color: Colors.grey[50],
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      child: Padding(
        padding: const EdgeInsets.all(12.0),
        child: Column(
          children: [
            Row(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: item.menuItemImage.isNotEmpty
                      ? Image.network(
                          item.menuItemImage,
                          width: 60,
                          height: 60,
                          fit: BoxFit.cover,
                          errorBuilder: (context, error, stackTrace) =>
                              Container(
                            width: 60,
                            height: 60,
                            color: Colors.grey[300],
                            child: const Icon(
                              Icons.restaurant,
                              color: Colors.grey,
                            ),
                          ),
                        )
                      : Container(
                          width: 60,
                          height: 60,
                          color: Colors.grey[300],
                          child:
                              const Icon(Icons.restaurant, color: Colors.grey),
                        ),
                ),
                const SizedBox(width: 12),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        item.menuItemName,
                        style: const TextStyle(
                          fontWeight: FontWeight.bold,
                          fontSize: 14,
                        ),
                      ),
                      const SizedBox(height: 4),
                      RatingBar.builder(
                        initialRating: _itemRatings[item.menuItemId] ?? 0,
                        minRating: 1,
                        itemSize: 24,
                        itemPadding:
                            const EdgeInsets.symmetric(horizontal: 2.0),
                        itemBuilder: (context, _) => const Icon(
                          Icons.star,
                          color: Colors.amber,
                        ),
                        onRatingUpdate: (rating) {
                          setState(() {
                            _itemRatings[item.menuItemId] = rating;
                          });
                        },
                      ),
                    ],
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            TextField(
              controller: _itemComments[item.menuItemId],
              decoration: InputDecoration(
                hintText: 'Votre avis sur ce plat (optionnel)',
                isDense: true,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                  borderSide: BorderSide(color: Colors.grey[300]!),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                  borderSide: BorderSide(color: Colors.grey[300]!),
                ),
                filled: true,
                fillColor: Colors.white,
              ),
              maxLines: 2,
              style: const TextStyle(fontSize: 13),
            ),
          ],
        ),
      ),
    );
  }
}
