// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbt_ZYvbzUwmcflqiHH8GL8BdAlAImlqI',
    appId: '1:574529156682:web:f5ebb766db3f851f8458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    authDomain: 'elcorazon-9595.firebaseapp.com',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByYPmtsEhRXWbmHQDtNLpHkw7IKpTwo10',
    appId: '1:574529156682:android:c79d9121ba193d8a8458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-_u76eEunEsbuCJFqE3juV9RrwWeJ-CU',
    appId: '1:574529156682:ios:b552dde7d1b9e0e98458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
    iosBundleId: 'com.elcorazon.fast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-_u76eEunEsbuCJFqE3juV9RrwWeJ-CU',
    appId: '1:574529156682:ios:ab0de5f23cd3f5dc8458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
    iosBundleId: 'com.example.elcoraFast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbt_ZYvbzUwmcflqiHH8GL8BdAlAImlqI',
    appId: '1:574529156682:web:47024d329f15b37c8458b3',
    messagingSenderId: '574529156682',
    projectId: 'elcorazon-9595',
    authDomain: 'elcorazon-9595.firebaseapp.com',
    storageBucket: 'elcorazon-9595.firebasestorage.app',
  );
}
